name = "xtrata"
compatibility_date = "2026-02-10"

[[d1_databases]]
binding = "DB"
database_name = "xtrata-db"
database_id = "YOUR-D1-DATABASE-ID"

[[r2_buckets]]
binding = "R2"
bucket_name = "xtrata-bucket"
