import { cloneSerializable } from '../framework/clone-serializable.mjs';

const powerupsRuntimeConfig = Object.freeze({
  initialPowerLevel: 1,
  maxPowerLevel: 3,
  spreadPowerDurationFrames: 720,
  lifePickupType: 'life',
  spreadPickupType: 'spread',
  spreadDropChance: 0.78,
  pickupSize: 16,
  pickupBaseDy: 1.2,
  pickupDyVariance: 0.7,
  pickupDriftDivisor: 10,
  pickupDriftAmplitude: 0.45,
  pickupExpireOffsetY: 28,
  shotProfiles: {
    powerLevel1: {
      cooldown: 8,
      centerDamage: 1,
      centerColor: '#fff08f',
      includeSideShots: false,
      includeWingShots: false
    },
    powerLevel2: {
      cooldown: 8,
      centerDamage: 1,
      centerColor: '#fff08f',
      includeSideShots: true,
      includeWingShots: false
    },
    powerLevel3: {
      cooldown: 6,
      centerDamage: 2,
      centerColor: '#fff08f',
      includeSideShots: true,
      includeWingShots: true
    }
  }
});

function buildRuntimeSnippet(config){
  const runtimeJson = JSON.stringify(config, null, 2);
  return [
    '(function(){',
    '  function createPowerupsRuntime(config){',
    '    var maxPowerLevel = Math.max(1, Number(config.maxPowerLevel) || 3);',
    '    var lifePickupType = config.lifePickupType || "life";',
    '    var spreadPickupType = config.spreadPickupType || "spread";',
    '    var spreadDropChance = Number(config.spreadDropChance);',
    '    if(!isFinite(spreadDropChance)) spreadDropChance = 0.78;',
    '    var pickupSize = Math.max(8, Number(config.pickupSize) || 16);',
    '    var pickupBaseDy = Number(config.pickupBaseDy);',
    '    if(!isFinite(pickupBaseDy)) pickupBaseDy = 1.2;',
    '    var pickupDyVariance = Number(config.pickupDyVariance);',
    '    if(!isFinite(pickupDyVariance)) pickupDyVariance = 0.7;',
    '    var pickupDriftDivisor = Number(config.pickupDriftDivisor);',
    '    if(!isFinite(pickupDriftDivisor) || pickupDriftDivisor === 0) pickupDriftDivisor = 10;',
    '    var pickupDriftAmplitude = Number(config.pickupDriftAmplitude);',
    '    if(!isFinite(pickupDriftAmplitude)) pickupDriftAmplitude = 0.45;',
    '    var pickupExpireOffsetY = Number(config.pickupExpireOffsetY);',
    '    if(!isFinite(pickupExpireOffsetY)) pickupExpireOffsetY = 28;',
    '    var spreadPowerDurationFrames = Math.max(1, Number(config.spreadPowerDurationFrames) || 720);',
    '    var shotProfiles = config.shotProfiles || {};',
    '',
    '    function clampPowerLevel(level){',
    '      var parsed = Number(level);',
    '      if(!isFinite(parsed)) return 1;',
    '      parsed = Math.floor(parsed);',
    '      if(parsed < 1) return 1;',
    '      if(parsed > maxPowerLevel) return maxPowerLevel;',
    '      return parsed;',
    '    }',
    '',
    '    function pickShotProfile(level){',
    '      var clamped = clampPowerLevel(level);',
    '      if(clamped >= 3 && shotProfiles.powerLevel3) return shotProfiles.powerLevel3;',
    '      if(clamped >= 2 && shotProfiles.powerLevel2) return shotProfiles.powerLevel2;',
    '      return shotProfiles.powerLevel1 || { cooldown: 8, centerDamage: 1, centerColor: "#fff08f" };',
    '    }',
    '',
    '    function getInitialState(){',
    '      return {',
    '        powerups: [],',
    '        powerLevel: clampPowerLevel(config.initialPowerLevel),',
    '        powerTimer: 0',
    '      };',
    '    }',
    '',
    '    function getPlayerShotPattern(state, player){',
    '      if(!state || !player) return null;',
    '      var profile = pickShotProfile(state.powerLevel);',
    '      var centerX = player.x + player.w * 0.5 - 2;',
    '      var baseY = player.y - 6;',
    '      var shots = [',
    '        { x: centerX, y: baseY, vx: 0, vy: -7.4, damage: profile.centerDamage || 1, color: profile.centerColor || "#fff08f" }',
    '      ];',
    '      if(profile.includeSideShots){',
    '        shots.push({ x: player.x + 1, y: baseY + 8, vx: -0.4, vy: -6.9, damage: 1, color: "#7efcff" });',
    '        shots.push({ x: player.x + player.w - 5, y: baseY + 8, vx: 0.4, vy: -6.9, damage: 1, color: "#7efcff" });',
    '      }',
    '      if(profile.includeWingShots){',
    '        shots.push({ x: centerX - 8, y: baseY + 12, vx: -1.05, vy: -6.3, damage: 1, color: "#ffde59" });',
    '        shots.push({ x: centerX + 8, y: baseY + 12, vx: 1.05, vy: -6.3, damage: 1, color: "#ffde59" });',
    '      }',
    '      return {',
    '        cooldown: Math.max(1, Number(profile.cooldown) || 8),',
    '        shots: shots',
    '      };',
    '    }',
    '',
    '    function maybeDrop(payload){',
    '      if(!payload || !payload.state || !payload.enemy) return;',
    '      var state = payload.state;',
    '      var profile = payload.profile;',
    '      if(!profile || !isFinite(profile.dropChance)) return;',
    '      var rand = typeof payload.rand === "function" ? payload.rand : Math.random;',
    '      var rewardsHazards = payload.rewardsHazards || null;',
    '      if(rand() > profile.dropChance) return;',
    '',
    '      if(rewardsHazards && typeof rewardsHazards.resolveDrop === "function"){',
    '        var resolved = rewardsHazards.resolveDrop({',
    '          profile: profile,',
    '          rand: rand',
    '        });',
    '        if(!resolved) return;',
    '        state.powerups.push({',
    '          x: payload.enemy.x + payload.enemy.w * 0.5 - pickupSize * 0.5,',
    '          y: payload.enemy.y + payload.enemy.h * 0.5 - pickupSize * 0.5,',
    '          w: pickupSize,',
    '          h: pickupSize,',
    '          dy: pickupBaseDy + rand() * pickupDyVariance,',
    '          type: resolved.pickupType || spreadPickupType,',
    '          sourceType: resolved.sourceType || "reward",',
    '          sourceId: resolved.sourceId || null,',
    '          pickupLabel: resolved.pickupLabel || null,',
    '          hazardEffect: resolved.hazardEffect || null,',
    '          phase: rand() * Math.PI * 2',
    '        });',
    '        return;',
    '      }',
    '',
    '      var type = rand() < spreadDropChance ? spreadPickupType : lifePickupType;',
    '      state.powerups.push({',
    '        x: payload.enemy.x + payload.enemy.w * 0.5 - pickupSize * 0.5,',
    '        y: payload.enemy.y + payload.enemy.h * 0.5 - pickupSize * 0.5,',
    '        w: pickupSize,',
    '        h: pickupSize,',
    '        dy: pickupBaseDy + rand() * pickupDyVariance,',
    '        type: type,',
    '        phase: rand() * Math.PI * 2',
    '      });',
    '    }',
    '',
    '    function tickPowerTimer(payload){',
    '      if(!payload || !payload.state) return;',
    '      var state = payload.state;',
    '      if(!(state.powerTimer > 0)) return;',
    '      state.powerTimer -= 1;',
    '      if(state.powerTimer <= 0){',
    '        state.powerTimer = 0;',
    '        state.powerLevel = 1;',
    '      }',
    '    }',
    '',
    '    function updatePowerups(payload){',
    '      if(!payload || !payload.state || !payload.player || typeof payload.rectsOverlap !== "function"){',
    '        return;',
    '      }',
    '',
    '      var state = payload.state;',
    '      var player = payload.player;',
    '      var tick = Number(payload.tick) || 0;',
    '      var maxLives = Math.max(1, Number(payload.maxLives) || 5);',
    '      var worldHeight = Number(payload.worldHeight) || 600;',
    '      var shared = payload.shared || null;',
    '      var rewardsHazards = payload.rewardsHazards || null;',
    '',
    '      for(var i = state.powerups.length - 1; i >= 0; i--){',
    '        var powerup = state.powerups[i];',
    '        powerup.y += powerup.dy;',
    '        powerup.x += Math.sin((tick + powerup.phase) / pickupDriftDivisor) * pickupDriftAmplitude;',
    '',
    '        if(payload.rectsOverlap(powerup, player)){',
    '          if(rewardsHazards && typeof rewardsHazards.applyPickup === "function"){',
    '            var applied = rewardsHazards.applyPickup({',
    '              state: state,',
    '              pickup: powerup,',
    '              shared: shared,',
    '              maxLives: maxLives',
    '            });',
    '            if(applied && applied.consumed){',
    '              state.powerups.splice(i, 1);',
    '              continue;',
    '            }',
    '          }',
    '',
    '          if(powerup.type === lifePickupType){',
    '            state.lives = Math.min(maxLives, state.lives + 1);',
    '            if(shared && shared.beep) shared.beep(760, 0.12, "sine", 0.05);',
    '          } else {',
    '            state.powerLevel = Math.min(maxPowerLevel, clampPowerLevel(state.powerLevel) + 1);',
    '            state.powerTimer = spreadPowerDurationFrames;',
    '            if(shared && shared.beep) shared.beep(660, 0.14, "sine", 0.05);',
    '          }',
    '          state.powerups.splice(i, 1);',
    '          continue;',
    '        }',
    '',
    '        if(powerup.y > worldHeight + pickupExpireOffsetY){',
    '          state.powerups.splice(i, 1);',
    '        }',
    '      }',
    '    }',
    '',
    '    return {',
    '      getInitialState: getInitialState,',
    '      getPlayerShotPattern: getPlayerShotPattern,',
    '      maybeDrop: maybeDrop,',
    '      tickPowerTimer: tickPowerTimer,',
    '      updatePowerups: updatePowerups',
    '    };',
    '  }',
    '',
    `  var runtimeConfig = ${runtimeJson};`,
    '  var runtimeHooks = game.__astroV2RuntimeHooks || {};',
    '  runtimeHooks.powerups = createPowerupsRuntime(runtimeConfig);',
    '  game.__astroV2RuntimeHooks = runtimeHooks;',
    '  if(typeof game.setV2RuntimeHooks === "function"){',
    '    game.setV2RuntimeHooks(runtimeHooks);',
    '  }',
    '',
    '  runtimePatch.runtime = runtimePatch.runtime || {};',
    '  runtimePatch.runtime.powerups = {',
    '    module: "powerups-runtime-hooks",',
    '    status: "active",',
    '    behaviorParity: "legacy-v1" ',
    '  };',
    '})();'
  ].join('\n');
}

export const powerupsRuntimeModule = {
  id: 'powerups-runtime-hooks',
  priority: 35,
  description: 'Injects runtime powerup/upgrade behavior hooks with legacy-parity values.',
  apply(artifact){
    artifact.runtimePatch.runtime = artifact.runtimePatch.runtime || {};
    artifact.runtimePatch.runtime.powerupsConfig = cloneSerializable(powerupsRuntimeConfig);

    artifact.runtimeSnippets = artifact.runtimeSnippets || [];
    artifact.runtimeSnippets.push(buildRuntimeSnippet(powerupsRuntimeConfig));
    return artifact;
  }
};
