import { rewardCatalog } from '../catalogs/rewards.mjs';
import { hazardCatalog } from '../catalogs/hazards.mjs';
import { cloneSerializable } from '../framework/clone-serializable.mjs';

const rewardsHazardsRuntimeConfig = Object.freeze({
  defaultDropChance: 0.13,
  hazardChance: 0.08,
  spreadPowerDurationFrames: 720,
  maxPowerLevel: 3,
  lifePickupType: 'life',
  spreadPickupType: 'spread',
  lifeRewardId: 'reward_supply_cache',
  spreadRewardId: 'reward_proto_upgrade',
  rewards: rewardCatalog,
  hazards: hazardCatalog
});

function buildRuntimeSnippet(config){
  const runtimeJson = JSON.stringify(config, null, 2);
  return [
    '(function(){',
    '  function createRewardsHazardsRuntime(config){',
    '    var rewardById = {};',
    '    var hazardById = {};',
    '    var rewards = Array.isArray(config.rewards) ? config.rewards : [];',
    '    var hazards = Array.isArray(config.hazards) ? config.hazards : [];',
    '    var i;',
    '',
    '    for(i = 0; i < rewards.length; i++){',
    '      if(rewards[i] && rewards[i].id){',
    '        rewardById[rewards[i].id] = rewards[i];',
    '      }',
    '    }',
    '',
    '    for(i = 0; i < hazards.length; i++){',
    '      if(hazards[i] && hazards[i].id){',
    '        hazardById[hazards[i].id] = hazards[i];',
    '      }',
    '    }',
    '',
    '    function resolveDrop(payload){',
    '      if(!payload || !payload.profile) return null;',
    '',
    '      var rand = typeof payload.rand === "function" ? payload.rand : Math.random;',
    '      var profileDrop = Number(payload.profile.dropChance);',
    '      var dropChance = isFinite(profileDrop) ? profileDrop : Number(config.defaultDropChance || 0.13);',
    '      if(rand() > dropChance) return null;',
    '',
    '      var hazardChance = Number(config.hazardChance || 0);',
    '      if(hazardChance > 0 && rand() < hazardChance && hazards.length > 0){',
    '        var hazard = hazards[Math.floor(rand() * hazards.length) % hazards.length];',
    '        return {',
    '          sourceType: "hazard",',
    '          sourceId: hazard.id,',
    '          pickupType: "hazard",',
    '          pickupLabel: hazard.label || "Hazard",',
    '          hazardEffect: hazard.effects || null',
    '        };',
    '      }',
    '',
    '      var spreadReward = rewardById[config.spreadRewardId] || null;',
    '      var lifeReward = rewardById[config.lifeRewardId] || null;',
    '      var spreadType = config.spreadPickupType || "spread";',
    '      var lifeType = config.lifePickupType || "life";',
    '',
    '      if(rand() < 0.78){',
    '        return {',
    '          sourceType: "reward",',
    '          sourceId: spreadReward ? spreadReward.id : null,',
    '          pickupType: spreadType,',
    '          pickupLabel: spreadReward ? spreadReward.label : "Power",',
    '          reward: spreadReward',
    '        };',
    '      }',
    '',
    '      return {',
    '        sourceType: "reward",',
    '        sourceId: lifeReward ? lifeReward.id : null,',
    '        pickupType: lifeType,',
    '        pickupLabel: lifeReward ? lifeReward.label : "Life",',
    '        reward: lifeReward',
    '      };',
    '    }',
    '',
    '    function applyPickup(payload){',
    '      if(!payload || !payload.state || !payload.pickup) return { consumed: false };',
    '',
    '      var state = payload.state;',
    '      var pickup = payload.pickup;',
    '      var shared = payload.shared || null;',
    '      var maxLives = Math.max(1, Number(payload.maxLives) || 5);',
    '      var maxPowerLevel = Math.max(1, Number(config.maxPowerLevel) || 3);',
    '      var spreadPowerDurationFrames = Math.max(1, Number(config.spreadPowerDurationFrames) || 720);',
    '      var lifeType = config.lifePickupType || "life";',
    '      var spreadType = config.spreadPickupType || "spread";',
    '',
    '      if(pickup.pickupType === lifeType || pickup.type === lifeType){',
    '        state.lives = Math.min(maxLives, state.lives + 1);',
    '        if(shared && shared.beep) shared.beep(760, 0.12, "sine", 0.05);',
    '        return { consumed: true, outcome: "life" };',
    '      }',
    '',
    '      if(pickup.pickupType === spreadType || pickup.type === spreadType){',
    '        state.powerLevel = Math.min(maxPowerLevel, Math.max(1, Math.floor(Number(state.powerLevel) || 1)) + 1);',
    '        state.powerTimer = spreadPowerDurationFrames;',
    '        if(shared && shared.beep) shared.beep(660, 0.14, "sine", 0.05);',
    '        return { consumed: true, outcome: "spread" };',
    '      }',
    '',
    '      if((pickup.pickupType === "hazard" || pickup.type === "hazard") && pickup.hazardEffect){',
    '        if(pickup.hazardEffect.weaponJamFrames){',
    '          state.weaponJamTimer = Math.max(state.weaponJamTimer || 0, Number(pickup.hazardEffect.weaponJamFrames) || 0);',
    '        }',
    '        if(shared && shared.beep) shared.beep(220, 0.14, "sawtooth", 0.05);',
    '        return { consumed: true, outcome: "hazard" };',
    '      }',
    '',
    '      return { consumed: false };',
    '    }',
    '',
    '    return {',
    '      resolveDrop: resolveDrop,',
    '      applyPickup: applyPickup',
    '    };',
    '  }',
    '',
    `  var runtimeConfig = ${runtimeJson};`,
    '  var runtimeHooks = game.__astroV2RuntimeHooks || {};',
    '  runtimeHooks.rewardsHazards = createRewardsHazardsRuntime(runtimeConfig);',
    '  game.__astroV2RuntimeHooks = runtimeHooks;',
    '  if(typeof game.setV2RuntimeHooks === "function"){',
    '    game.setV2RuntimeHooks(runtimeHooks);',
    '  }',
    '',
    '  runtimePatch.runtime = runtimePatch.runtime || {};',
    '  runtimePatch.runtime.rewardsHazards = {',
    '    module: "rewards-hazards-runtime-hooks",',
    '    status: "active",',
    '    hazardChance: runtimeConfig.hazardChance,',
    '    behaviorParity: "legacy-v1-safe"',
    '  };',
    '})();'
  ].join('\n');
}

export const rewardsHazardsRuntimeModule = {
  id: 'rewards-hazards-runtime-hooks',
  priority: 32,
  description: 'Injects reward/hazard drop and pickup effect resolution hooks.',
  apply(artifact){
    artifact.runtimePatch.runtime = artifact.runtimePatch.runtime || {};
    artifact.runtimePatch.runtime.rewardsHazardsConfig = cloneSerializable(rewardsHazardsRuntimeConfig);

    artifact.runtimeSnippets = artifact.runtimeSnippets || [];
    artifact.runtimeSnippets.push(buildRuntimeSnippet(rewardsHazardsRuntimeConfig));
    return artifact;
  }
};
